config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  root "toot#index"
  get "/timeline", to: "toot#timeline", as: :timeline
  delete "/toot/delete/:id", to: "toot#delete", as: :delete_toot

  get "/users", to: "user#index", as: :toot_users
  get "/users/:id", to: "user#show", as: :user

  get "/users/follow/:id", to: "user#follow", as: :follow_user
  get "/users/unfollow/:id", to: "user#unfollow", as: :unfollow_user
  post "/toot/create", to: "toot#create", as: :create_toot
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/toot.rb
class Toot < ApplicationRecord
  belongs_to :user

  default_scope { order(created_at: :desc)}

  def self.toots_for(ids)
    where(user_id: ids).order(created_at: :desc)
  end

end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :toots

  mount_uploader :avatar, AvatarUploader

  serialize :following, Array
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

   def configure_permitted_parameters
     keys = [:username, :name, :email, :password, :password_confirmation, :city, :state, :bio, :avatar]
     devise_parameter_sanitizer.permit(:sign_up, keys: keys)
     devise_parameter_sanitizer.permit(:account_update, keys: keys)
   end
end

app/controllers/toot_controller.rb
class TootController < ApplicationController
  before_action :authenticate_user!, except: [ :index ]

  def index
  end

def create
  @toot = current_user.toots.create(toot_params)
  @toot.save!

  redirect_to user_path(id: current_user.id)
end

def delete
  @toot = Toot.find(params[:id])
  @toot.destroy!

  redirect_to timeline_path

  def timeline
    ids = current_user.following
    ids.push(current_user.id.to_s)

    @toots = Toot.toots_for(ids)
  end

  private

  def toot_params
    params.require(:toot).permit(:message)
  end

end

app/controllers/user_controller.rb
class UserController < ApplicationController
  before_action :authenticate_user!

  def index
    @users = User.all
  end

  def show
    @user = User.find(params[:id])
    @toot = Toot.new
  end

  def follow
    current_user.following.push(params[:id])
    current_user.save!
    redirect_to user_path(id: params[:id])
  end

  def unfollow
    current_user.following.delete(params[:id])
    current_user.save!
    redirect_to user_path(id: params[:id])
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/toot_helper.rb
module TootHelper
end

app/helpers/user_helper.rb
module UserHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Tooter</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <nav class="navbar navbar-default navbar-fixed-top">
      <div class="container">
        <% if user_signed_in? %>
          <p class="navbar-text">Signed in as @<%= current_user.username %></p>
          <%= link_to "Sign Out", destroy_user_session_url, method: :delete, class: "btn btn-default navbar-btn" %>
        <% else %>
          <%= link_to "Sign In", new_user_session_url, class: "btn btn-default navbar-btn" %>
        <% end %>
        <%= link_to "Home", root_url, class: "navbar-text"%>
        <%= link_to "Users", toot_users_url, class: "navbar-text"%>
        <%= link_to "Timeline", timeline_url, class: "navbar-text"%>

        <% if user_signed_in? %>
          <%= link_to "Profile", user_path(id: current_user.id), class: "navbar-text"%>
        <% end %>
      </div>
    </nav>

    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>

    <div class="container">
      <%= yield %>
    </div>
  </body>
</html>

app/views/shared/_toot.html.erb
<div class="toot">
  <%= image_tag toot.user.avatar.url, height: 20 %>
  @<%= toot.user.username %>
  <span class="date-in-words"><%= time_ago_in_words(toot.created_at) %> ago</span>
  <p><%= toot.message %></p>
  <% if current_user == toot.user %>
    <%= link_to "Delete", delete_toot_path(id: toot.id), method: :delete, class: "btn btn-danger" %>
  <% end %>
</div>

app/views/toot/index.html.erb
<div class="jumbotron">
  <h1>Welcome to Tooter</h1>
  <p>Make toots all day long</p>
</div>

app/views/toot/timeline.html.erb
<h1>@<%= current_user.username %>'s Timeline</h1>

<% @toots.each do |toot| %>
  <%= render 'shared/toot', toot: toot %>
<% end %>

app/views/user/_new_toot.html.erb
<div class="toot-form">
    <%= form_for toot, url: create_toot_path do |f| %>
      <%= f.label :message %><br />
      <%= f.text_area :message, autofocus: true, cols: 60, rows: 5 %>
      <br>
      <%= f.submit "Toot It!", class: "btn btn-primary" %>
    <% end %>
  </div>

app/views/user/index.html.erb
<h1>Users</h1>

<% @users.each do |user| %>
<div class="thumbnail-container">
  <div class="thumbnail">
    <%= image_tag user.avatar.url unless user.avatar.url == nil %>
    <div class="caption">
      <%= link_to "@#{user.username}", user_url(user) %>
      <p>
        <%= user.name %> <br>
        <%= user.city %>, <%= user.state %>
      </p>
    </div>
  </div>
</div>
<% end %>

app/views/user/show.html.erb
<h1>@<%= @user.username  %></h1>

<div class="bio-column">
  <% if @user.avatar.url %>
    <%= image_tag @user.avatar.url, width: 200 %>
  <% else %>
    <%= image_tag 'user-profile-icon.jpg', width: 200 %>
  <% end %>

  <p><%= @user.name %></p>
  <p><%= @user.city %>, <%= @user.state %></p>
  <p><%= @user.email %></p>
  <p><%= @user.bio %></p>

  <br>
</div>

<div class="toot-column">

  <% if @user == current_user %>
    <%= render 'new_toot', toot: @toot %>
  <% else %>
    <% if current_user.following.include?(@user.id.to_s) %>
      <%= link_to "Unfollow", unfollow_user_url(id: @user.id), class: "btn btn-danger" %>
    <% else %>
      <%= link_to "Follow", follow_user_url(id: @user.id), class: "btn btn-primary" %>
    <% end %>
  <% end %>

  <% @user.toots.each do |toot| %>
    <%= render 'shared/toot', toot: toot %>
  <% end %>
</div>